### ISSUE TITLE
Bug with formula objects and their namespace

### ISSUE THREAD

**Issue by Martin-Jung** [ElliotDovers/scampr#5]
Cool package!
I tried to do a simple model selection example by wrapping the `scampr` call into a function, however it seems as if the formula object is not correctly passed on to TMB?. 

**To reproduce:**
```
# Get the flora data for one of the species
dat_po <- flora$po$sp1
dat_pa <- flora$pa

# obtain a sample of 10,000 quadrature points for the point process model
set.seed(1)
quad.pts <- flora$quad[sample(1:nrow(flora$quad), 10000, replace = F), ]
set.seed(NULL)

# Attach the quadrature points to the presence-only data
dat_po <- rbind.data.frame(dat_po, quad.pts)

# Ensure the "response" variable in each data set shares the same name
dat_po$presence <- dat_po$pres
dat_pa$presence <- dat_pa$sp1

# Fit models without a latent effects
# Point Process Model
f <- function(form){
  m.ipp <- scampr(form, dat_po, include.sre = F,se = T)
  return(AIC(m.ipp))
}

# Fit a series of models
f(presence ~ MNT + D.Main)
f(presence ~ MNT + D.Main + Rain)

```
The error:
> Error in scampr(form, dat_po, include.sre = F, se = T) : 
>   object 'form' not found
![grafik](https://github.com/ElliotDovers/scampr/assets/3788377/d378badf-0852-4e90-b0cc-3fcbd76e102e)

  Without the function it works, e.g.
`  scampr(presence ~ MNT + D.Main, dat_po, include.sre = F,se = T)`

**Comment by ElliotDovers** [comment]
Thanks for pointing this out and checking out the package generally!

This looks like a scoping issue - I'll try and debug soon

**Comment by ElliotDovers** [comment]
I've fixed it so that the `formula` (and `bias.formula`) are scoped properly before being sent to the internal call of `get.TMB.input.data()`.

Thanks again for pointing this out. I'm going to close this issue now

**Comment by Martin-Jung** [comment]
Thanks a lot! Will test out
